#!/usr/bin/env groovy

node {
  stage("Stage 1") {
    echo "Test"
    // echo "Param: ${STRING01}"
    func01()
    showWorkspace()
  }
}


def func01(){
  stage("Stage 2") {
    echo "Pushout:  ${STRING01}"

    startStr = "/Testing/sandbox/Curation/top_AWS_Athena_to_Step_Func_Curation.jmx"
    String[] pathSplit =  startStr.split('/')
    cntChunks = pathSplit.length;
    echo "X: ${cntChunks[5]}"

    // - TEST_BASE_PATH
    // The root path
    // eg: ${WORKSPACE}/Testing

    // - TEST_PATH_TO_JMX_FILE
    // relative path to primary JMX file
    // eg: sandbox/Curation/top_AWS_Athena_to_Step_Func_Curation.jmx

    // - TEST_SOURCE_CSV_FILE
    // name of the test metadata CSV file
    // eg: BTCA_curate_001.csv


  }
}

def showWorkspace(){
  stage("Stage 3") {
    echo "Pushout:  ${WORKSPACE}"
  }
}
